spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/testauth
    username: testauthuser
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver